language: cpp
compiler:
- gcc
env:
  global:
  - MAKE_CMD="make -j2"  
os:
- linux
dist: trusty
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - lcov
    - libgtest-dev
    - cmake-data
    - cmake
    - libboost-dev
install:
  # gtest workaround - compile library
   - cd /usr/src/gtest
   - sudo cmake .
   - sudo make
   - sudo mv libgtest* /usr/lib/
   - cd "${TRAVIS_BUILD_DIR}"
# -- workaround end
script:
- cd ${TRAVIS_BUILD_DIR}
- mkdir release_build
- cd release_build
- cmake ..
- make package
- cd ${TRAVIS_BUILD_DIR}
- mkdir coverage_build
- cd coverage_build
- cmake -DCMAKE_BUILD_TYPE=Coverage ..
- make ip_filter_coverage
after_success:
- cd ${TRAVIS_BUILD_DIR}/coverage_build
- lcov --list coverage.info
- bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage
  reports"
- cd ${TRAVIS_BUILD_DIR}
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -X PUT -T ${TRAVIS_BUILD_DIR}/release_build/ip_filter-1.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uortus-art:$BINTRAY_API_KEY "https://api.bintray.com/content/ortus-art/course/ip_filter/1.0.$TRAVIS_BUILD_NUMBER/pool/main/m/ip_filter/ip_filter-1.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
